version: "3.4"

services:
  api:
    build: ./BackEnd
    container_name: dotnet_api
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge