apiVersion: 1

datasources:
  - name: PostgreSQL-HA
    type: postgres
    url: postgres-haproxy:5432
    access: proxy
    user: grafana
    secureJsonData:
      password: grafanapass
    database: grafana
    isDefault: false
    jsonData:
      sslmode: disable

  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      timeInterval: 10s
    basicAuth: false
    isDefault: true
    version: 1
    editable: false        
    

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    jsonData:
       derivedFields:
        - datasourceUid: tempo
          matcherRegex: "\u0022traceid\u0022:\u0022(\\w+)\u0022"
          name: TraceId
          url: '$${__value.raw}'  
