global:
  resolve_timeout: 5m

route:
  receiver: 'email-notification'

receivers:
  - name: 'email-notification'
    email_configs:
      - to: 'xxxx@cmu.ac.th'
        from: 'xxxx@cmu.ac.th'
        smarthost: 'xx.xx.xx.xx:25'
        send_resolved: true
        require_tls: false
